[project]
name = "gioiaanalysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=0.3.30",
    "openai>=1.99.9",
    "pathlib>=1.0.1",
    "pydantic-settings>=2.10.1",
    "python-docx>=1.2.0",
]
